# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StringReader
                                 A QGIS plugin
 Reads string files
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-11
        copyright            : (C) 2020 by Basil Eric C. Rabi
        email                : ericbasil.rabi@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# pylint: disable=import-error

def classFactory(iface):
    from .string_reader import StringReader
    return StringReader(iface)
